- name: Setup frontend  instances on AWS Environment with nginx
  hosts: webservers
  gather_facts: False
  tasks:
    - import_tasks: tasks/ec2_setup_frontend.yml
- name: Setup backend  instances on AWS Environment with nginx and spring boot microservice
  hosts: microservices
  gather_facts: False
  tasks:
    - import_tasks: tasks/ec2_setup_backend.yml