- name: ensure nginx is at the latest version
  apt: name=nginx state=latest
  become: yes
- name: start nginx
  service:
      name: nginx
      state: started
  become: yes
- name: copy the nginx config file and restart nginx
  copy:
    src: .,/files/static_site.cfg
    dest: /etc/nginx/sites-available/static_site.cfg
  become: yes    
- name: create symlink
  file:
    src: /etc/nginx/sites-available/static_site.cfg
    dest: /etc/nginx/sites-enabled/default
    state: link
  become: yes
- name: Copying index file to instance nginx server
  template:
    src: ../files/static-site-src/index.html.j2
    dest: /home/ubuntu/static-site/index.html
- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes