- name: add the webservers frontend A to the load balancer
  local_action: ec2_elb
  args:
    instance_id: "{{ item.id }}"
    ec2_elbs: "frontend-load-balancer"
    state: present
    region: "{{ aws_region }}"
  with_items: "{{ ec2instance_frontend_a.instances }}"
  ignore_errors: yes
- name: add the webservers frontend B to the load balancer
  local_action: ec2_elb
  args:
    instance_id: "{{ item.id }}"
    ec2_elbs: "frontend-load-balancer"
    state: present
    region: "{{ aws_region }}"
  with_items: "{{ ec2instance_frontend_b.instances }}"
  ignore_errors: yes
