- name: add the webservers frontend A to the load balancer
  local_action: ec2_elb
  args:
    instance_id: "{{ item.id }}"
    ec2_elbs: "frontend-load-balancer"
    state: present
<<<<<<< HEAD
    region: "{{  aws_region }}"
=======
    region: "{{ aws_region }}"
>>>>>>> f086301ef28d717e3eaf4ea3058e8825b43cf1a3
  with_items: "{{ ec2instance_frontend_a.instances }}"
  ignore_errors: yes
- name: add the webservers frontend B to the load balancer
  local_action: ec2_elb
  args:
    instance_id: "{{ item.id }}"
    ec2_elbs: "frontend-load-balancer"
    state: present
<<<<<<< HEAD
    region: "{{  aws_region }}"
  with_items: "{{ ec2instance_frontend_b.instances }}"
  ignore_errors: yes
=======
    region: "{{ aws_region }}"
  with_items: "{{ ec2instance_frontend_b.instances }}"
  ignore_errors: yes
>>>>>>> f086301ef28d717e3eaf4ea3058e8825b43cf1a3
